/*
 * JSocket Wrench
 * 
 * Copyright (C) act365.com October 2003
 * 
 * Web site: http://www.act365.com/wrench
 * E-mail: developers@act365.com
 * 
 * The JSocket Wrench library adds support for low-level Internet protocols
 * to the Java programming language.
 * 
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *  
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with 
 * this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_act365_net_GeneralSocketInputStream */

#ifndef _Included_com_act365_net_GeneralSocketInputStream
#define _Included_com_act365_net_GeneralSocketInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_act365_net_GeneralSocketInputStream
 * Method:    _read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_act365_net_GeneralSocketInputStream__1read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     com_act365_net_GeneralSocketInputStream
 * Method:    _close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_act365_net_GeneralSocketInputStream__1close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
