O_TARGET := jni.o

O_OBJS = \
	SocketUtils.o \
	com_act365_net_GeneralSocketImpl.o \
	com_act365_net_GeneralSocketInputStream.o \
	com_act365_net_GeneralSocketOutputStream.o \
	com_act365_net_SocketWrenchSession.o \
	com_act365_net_GeneralDatagramSocketImpl.o

include $(TOPDIR)/Rules.make

